### ISSUE TITLE
Insert of multiple line tickets 8.5.3

### ISSUE THREAD

**Issue by Bflatt** [NCRCounterpointAPI/APIGuide#82] opened 2017-12-01 19:00 UTC
When inserting ticket with mutiulple lines we are receiving this error  
exact same code works fine win single line or 8.5.2.1
was there a change to the hdr or line layout for 853? 
{
    "Documents": [],
    "ErrorCode": "ERROR_UNKNOWN",
    "Message": "An error occurred during AddDocument POST: Missing type map configuration or unsupported mapping.\r\n\r\nMapping types:\r\nPO_VEND_ITEM -> PO_VEND_ITEM\r\nCPAPI.Model_846.PO_VEND_ITEM -> NCR.CP.CPAPI.Base.Model.PO_VEND_ITEM\r\n\r\nDestination path:\r\nPO_VEND_ITEM\r\n\r\nSource value:\r\nCPAPI.Model_846.PO_VEND_ITEM,    at CPAPI.V853.DocumentBusiness_853.PopulateDefaults(PS_DOC_HDR documentHeader, String workgroupId)\r\n   at CPAPI.V853.DocumentBusiness_853.AddDocument(PS_DOC_HDR_POST documentPost, PS_TAX_VIEW taxView, String workgroup)"

**Comment by mbantug** [comment] 2017-12-01 19:09
No change in the layout, this is a bug.  It is the same root cause as https://github.com/NCRCounterpointAPI/APIGuide/issues/70.  The fix for this will be in the next release.

**Comment by Bflatt** [comment] 2017-12-01 19:11
And when might that be?


[cid:image001.jpg@01D2DEDA.41EDDC70]

Bill Flatt
Mainspring, LLC
6060 S American Plaza St E | Suite 300 | Tulsa, OK | 74135
Phone: 800.865.1427 x2827 | Local: 918.317.0707
bflatt@mainspring.net<mailto:bflatt@mainspring.net> | www.mainspring.net<http://www.mainspring.net/> | Need Help?<mailto:support@mainspring.net>
[cid:image002.png@01D2DEDA.41EDDC70]<https://www.facebook.com/MainSpringRetailSolutions/>[cid:image003.png@01D2DEDA.41EDDC70]<https://twitter.com/MainspringPOS> [cid:image004.png@01D2DEDA.41EDDC70] <http://www.linkedin.com/company/576462>  [cid:image005.png@01D2DEDA.41EDDC70] <mailto:support@mainspring.net>

**Comment by Bflatt** [comment] 2017-12-01 19:12
and when might this be?

**Comment by Bflatt** [comment] 2017-12-01 19:14
any workaround known? 
this is a pretty devastating bug.

**Comment by Bflatt** [comment] 2017-12-05 13:07
Turns out this may not be a bug, but a CP data problem.  After extensive testing, I discovered this is related to the po_vend_item table.  It was not multiple ticket lines, but instead specific items which would error on ticket line insert.  Removing all vendor items, saving the item, and rekeying corrects the issue.  I attempted a complete export and restore of the PO_VEND_ITEM table with data interchange, but this did not correct the issue.   The system in question is a recent V7 migration.  I suspect this may be a malformed record problem.   I am going to work on ways to clean up the data externally.   I thought this information may assist with you research into this as a potential bug.

**Comment by Bflatt** [comment] 2017-12-07 17:33
Correction to the last post. THe problem is actually when im_item.vend_item_no= im_item.item_no.   Changing or nulling the vendor item number in im_item AND po_vend_item corrects the error. 
This is still a bug, but with a reasonable workaround.

**Closed** 2018-01-18 20:49 UTC
