### ISSUE TITLE
500 Error - Customer Post

### ISSUE THREAD

**Issue by pheslop** [NCRCounterpointAPI/APIGuide#3] opened 2017-02-10 19:04 UTC
Hi Mike!

We have a few people around here testing the API.  One of our users is having an issue posting a customer record.  I think it may be related to a workgroup mismatch or template customer, but it is returning an error 500, which is why I am submitting it here

POST
URL: https://173.209.108.212:52000/Customer

Used the same HTTP headers as PUT request (which is working well)

    'Content-Type':'application/json'
    'Accept':'application/json'
    'APIKey':'secret_api_key'
    'Authorization':'Basic xxxxxxxxxxxxxxxxxxxxxxxxxxx='

Request body:
=============
Two JSON body tested:

1. With "AR_CUST":

{"AR_CUST": {"NAM": "Arttest3 Arttest4", "ZIP_CODE": "22334", "LST_NAM": "Arttest4", "ADRS_1": "Novosibirsk", "CUST_TYP": "Cash", "PROF_DAT_3": "2017-02-01T00:00:00.0000000", "CNTRY": "US", "PROF_DAT_2": "1982-12-03T00:00:00.0000000", "FST_NAM": "Arttest3", "PHONE_1": "89998887766", "STATE": "Guam", "CITY": "Defaultcity", "STR_ID": "AG1", "SLS_REP": "AG"}}

Server response:
----------------
HTTP Status code: 500 Internal Server Error

ErrorCode: ERROR_UNKNOWN

Message:  An error occurred during AddCustomer: Object reference not set to an in
stance of an object.,    at System.Object.GetType()
   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SetFilter[T](IDb
Command dbCmd, String name, Object value)
   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.SingleById[T](ID
bCommand dbCmd, Object value)
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbCon
n, Func`2 filter)
   at CPAPI.Repositories_846.CustomerRepository_846.CPAPI.Repositories_8
46.ICustomerRepository.GetCustomerById(String custNo)
   at CPAPI.Business_846.CustomerBusiness_846.AddCustomer(AR_CUST_POST c
ustomerEdit, String workgroupId)

**Comment by MikeRitchie** [comment] 2017-02-10 19:29
Here's a few quick things to know/check:
* CUST_TYP should be "C", not "Cash" (but this isn't the thing causing your error
* The error is most likely caused trying to figure out the proper, next CUST_NO to assign to the new customer. If no workgroup is provided (as is the case for you), the API will grab the WRKGRP_ID from the user passed into the basic auth header (SY_USR.WRKGRP_ID). Please be sure that workgroup is a valid workgroup with a valid NXT_CUST_NO value.
* If you prefer, you can explicitly pass in a workgroup ID like this:
{
  "Workgroup" : "3",  
  "AR_CUST": {
    "NAM": "Arttest3 Arttest4",
    "ZIP_CODE": "22334",
    "LST_NAM": "Arttest4",
    "ADRS_1": "Novosibirsk",
    "CUST_TYP": "C",
    "PROF_DAT_3": "2017-02-01T00:00:00.0000000",
    "CNTRY": "US",
    "PROF_DAT_2": "1982-12-03T00:00:00.0000000",
    "FST_NAM": "Arttest3",
    "PHONE_1": "89998887766",
    "STATE": "Guam",
    "CITY": "Defaultcity",
    "STR_ID": "AG1",
    "SLS_REP": "AG"
  }
}

* Also note that any value not provided in your JSON, the API will copy from the template customer, just like Counterpoint does. Again, the template customer comes from the workgroup. If there is no template customer, you must pass all required fields in the JSON.

**Comment by MikeRitchie** [comment] 2017-02-10 19:47
Looking a little deeper, this is almost certainly caused by a null template customer for the workgroup being used. Two solutions:
1. Make sure there's a template customer set for the workgroup assigned to the Counterpoint user specified in your authorization header
2. Explicitly specify a workgroup in the JSON you are submitting, for a workgroup that contains a valid Customer number.

We'll look at making this more robust in the future, including better error reporting.

**Comment by akoppelkam** [comment] 2017-02-10 23:59
Thanks for the quick reply Mike! Ill check it out and let you know how I make out

**Comment by akoppelkam** [comment] 2017-02-20 21:16
Hey! So we were able to trouble shoot the issue and get it working! I believe the issue had to do with the workgroup having the always auto assign option checked for the customer number. When that was unselected it started working.

**Closed** 2017-02-22 21:11 UTC
